In [1]:
# Import Dependencies
import pandas as pd
from pathlib import Path

In [2]:
# Create a path to the csv and read it into a Pandas DataFrame
filepath = Path("Resources/movie_scores.csv")

movies_df = pd.read_csv(filepath)
movies_df.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.2,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.4,...,2.55,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5

In [7]:
# Figure out the minimum and maximum IMDB user vote count
raters_df = movies_df.sort_values("IMDB_user_vote_count", ascending=False)
raters_df.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
14,The Imitation Game (2014),90,92,73,8.2,8.1,5.0,4.6,4.50,4.60,...,4.05,4.5,4.5,3.5,4.0,4.0,566,334164,8055,0.4
65,Birdman (2014),92,78,88,8.0,7.9,4.0,3.7,4.60,3.90,...,3.95,4.5,4.0,4.5,4.0,4.0,1171,303505,4194,0.3
88,Mad Max: Fury Road (2015),97,88,89,8.7,8.3,4.5,4.3,4.85,4.40,...,4.15,5.0,4.5,4.5,4.5,4.0,2375,292023,10509,0.2
74,The Hobbit: The Battle of the Five Armies (2014),61,75,59,7.0,7.5,4.5,4.3,3.05,3.75,...,3.75,3.0,4.0,3.0,3.5,4.0,903,289464,15337,0.2
44,Kingsman: The Secret Service (2015),75,84,58,7.9,7.8,4.5,4.2,3.75,4.20,...,3.90,4.0,4.0,3.0,4.0,4.0,1054,272204,15205,0.3

In [21]:
# Create bins in which to place values based upon IMDB vote count
bins = [0, 1000, 10000, 25000, 50000, 100000, 150000, 200000, 250000, 300000, 350000]
# Create labels for these bins
bin_labels = ["Under 1,000 Voters", "1,000 to 10,000 Votes", "10K to 25K Votes", "25K to 50K Votes", "50K to 100K Votes", 
              "100K to 150K Votes", "150K to 200K Votes", "200K to 250K Votes", "250K to 300K Votes", "Greater than 300K Votes"]

In [22]:
# Slice the data and place it into bins
raters_df["IMDB Popularity"] = pd.cut(raters_df["IMDB_user_vote_count"], bins, labels=bin_labels)

In [23]:
# Place the data series into a new column inside of the DataFrame
raters_df.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference,IMDB Popularity
14,The Imitation Game (2014),90,92,73,8.2,8.1,5.0,4.6,4.50,4.60,...,4.5,4.5,3.5,4.0,4.0,566,334164,8055,0.4,Greater than 300K Votes
65,Birdman (2014),92,78,88,8.0,7.9,4.0,3.7,4.60,3.90,...,4.5,4.0,4.5,4.0,4.0,1171,303505,4194,0.3,Greater than 300K Votes
88,Mad Max: Fury Road (2015),97,88,89,8.7,8.3,4.5,4.3,4.85,4.40,...,5.0,4.5,4.5,4.5,4.0,2375,292023,10509,0.2,250K to 300K Votes
74,The Hobbit: The Battle of the Five Armies (2014),61,75,59,7.0,7.5,4.5,4.3,3.05,3.75,...,3.0,4.0,3.0,3.5,4.0,903,289464,15337,0.2,250K to 300K Votes
44,Kingsman: The Secret Service (2015),75,84,58,7.9,7.8,4.5,4.2,3.75,4.20,...,4.0,4.0,3.0,4.0,4.0,1054,272204,15205,0.3,250K to 300K Votes

In [27]:
# Create a GroupBy object based upon "IMDB User Votes Group"
IMDB_df = raters_df.groupby("IMDB Popularity")

print(IMDB_df["IMDB Popularity"].count())

# Find how many rows fall into each bin


# Get the average of each of the first 5 rating columns within the GroupBy object
IMDB_df[["RottenTomatoes", "RottenTomatoes_User", "Metacritic", "Metacritic_User", "IMDB"]].mean()

IMDB Popularity
Under 1,000 Voters          7
1,000 to 10,000 Votes      39
10K to 25K Votes           44
25K to 50K Votes           24
50K to 100K Votes          16
100K to 150K Votes          5
150K to 200K Votes          2
200K to 250K Votes          2
250K to 300K Votes          5
Greater than 300K Votes     2
Name: IMDB Popularity, dtype: int64

,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB
IMDB Popularity,,,,,
"Under 1,000 Voters",80.142857,72.428571,68.285714,7.185714,6.971429
"1,000 to 10,000 Votes",62.589744,66.666667,60.410256,6.987179,6.835897
10K to 25K Votes,55.090909,56.886364,55.568182,6.034091,6.452273
25K to 50K Votes,55.833333,59.916667,54.791667,6.116667,6.566667
50K to 100K Votes,67.875000,69.375000,63.125000,6.718750,7.018750
100K to 150K Votes,40.400000,57.400000,45.400000,6.160000,6.600000
150K to 200K Votes,58.500000,64.000000,62.000000,5.550000,5.950000
200K to 250K Votes,76.000000,82.500000,63.000000,6.900000,7.350000
250K to 300K Votes,75.800000,83.600000,68.800000,7.460000,7.760000
Greater than 300K Votes,91.000000,85.000000,80.500000,8.100000,8.000000